# Generated by Django 4.2.6 on 2023-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Non critical'), (3, 'High'), (4, 'Critical')], default=1, verbose_name='Priority')),
                ('text', models.TextField(verbose_name='Task text')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority'],
            },
        ),
    ]
